---
  reference_by_usb: true
  play_from_video: false
  video_files:
    - ' '    
    - ' '
  cameras:
  # Right camera to connected to USB port 0-1
    - '0-1'
  # Left camera to connected to USB port 0-5
    - '0-5'
  calib_files:
  # Right camera data
    - 'params/intrinsics/5002_0.yaml'   
  # Left camera data
    - 'params/intrinsics/5002_1.yaml'
  apply_KD: false
  display: true
  print_markers: true
  remote_ip: "127.0.0.1"
  remote_port: 5000
  fps: 50
  gain: 10
  exposure: 30
